server:
  port: 8089
  uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.96.17:3306/steel?characterEncoding=utf8&useAffectedRows=true&allowMultiQueries=true
    #url: jdbc:mysql://localhost:3306/plustest?characterEncoding=utf8
    username: root
    password: p7%xiIdSy@eJhq
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 172.17.96.6
    port: 6379
    password: abcABC123
  http:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB
#mybatis 配置
mybatis:
  mapper-locations: classpath:com/shiro/steel/mapper/xml/*.xml
  type-aliases-package: com.shiro.steel.entity

logging:
  config: classpath:log4j2.xml
  level:
    com.shiro.steel.mapper: info
cos:
  accessKeyId: AKID39AA3AN5tVwJdosmDYqwUoBRgniWKrHb
  accessKeySecret: IUXVIvRl27A32riT2hG2lO4hRUvKdsy3
  endpoint: ap-shanghai
  bucket: fw-1300712873
  dir: steel/
